# Generated by Django 4.2.13 on 2024-06-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIcampoprime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pista',
        ),
        migrations.AddField(
            model_name='reserva',
            name='recinto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APIcampoprime.recinto', verbose_name='Recinto'),
        ),
        migrations.DeleteModel(
            name='Pista',
        ),
    ]
