# Generated by Django 4.2.13 on 2024-06-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcampoprime', '0002_remove_recinto_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='precio_por_hora',
            field=models.FloatField(),
        ),
    ]
