# Generated by Django 4.2.13 on 2024-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcampoprime', '0003_alter_recinto_precio_por_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recintos'),
        ),
    ]
