# Generated by Django 4.2.13 on 2024-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcampoprime', '0004_alter_recinto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='precio_por_hora',
            field=models.FloatField(default=None),
        ),
    ]
