# Generated by Django 4.2.13 on 2024-06-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcampoprime', '0005_alter_recinto_precio_por_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='hora_fin',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='hora_inicio',
            field=models.FloatField(default=None),
        ),
    ]
