# Generated by Django 4.2.13 on 2024-06-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcampoprime', '0007_alter_recinto_hora_fin_alter_recinto_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recinto',
            name='imagen',
        ),
    ]
